# Generated by Django 5.1.7 on 2025-03-31 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppping1',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppping2',
            new_name='topping2',
        ),
    ]
