# Generated by Django 5.1.7 on 2025-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaShop', '0002_rename_toppping1_pizza_topping1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
